version: '3'

services:
  sql.data:
    image: nileshgule/sqlclient-datadaysg
    build:
      context: ../src/TechTalksDB
      dockerfile: Dockerfile
      
  techtalks.api:
    image: nileshgule/techtalksapi-datadaysg
    build:
      context: ../src/TechTalksAPI
      dockerfile: Dockerfile
    depends_on:
      - sql.data
    ports:
      - "8080:80"